<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Mozambique Malaria Epidemiology Summary – Malaria Country Profiles</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-e118b92792f507caea417ea076e89dbd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Malaria Country Profiles</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-countries" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Countries</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-countries">    
        <li>
    <a class="dropdown-item" href="../countries/tanzania.html">
 <span class="dropdown-text">Tanzania</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../countries/cameroon.html">
 <span class="dropdown-text">Cameroon</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../countries/benin.html">
 <span class="dropdown-text">Benin</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../countries/burkina-faso.html">
 <span class="dropdown-text">Burkina Faso</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../countries/nigeria.html">
 <span class="dropdown-text">Nigeria</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../countries/mozambique.html">
 <span class="dropdown-text">Mozambique</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../countries/angola.html">
 <span class="dropdown-text">Angola</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Mozambique Malaria Epidemiology Summary</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 data-anchor-id="introduction">1. Introduction</h2>
<p>Mozambique sits in southeastern Africa within the WHO African Region, among the four highest-burden malaria countries globally with a population of roughly 34.6 million people as of 2024. What sets Mozambique apart is that malaria control here is not a targeted, geographically bounded effort the entire population is classified as at high risk, with no low-risk or malaria-free zones anywhere in the country. This universal exposure, combined with perennial transmission and a north-east to south-west burden gradient, makes malaria control central to the country’s health system, accounting for over a quarter of outpatient visits and more than a third of hospital admissions.</p>
<hr>
</section>
<section id="summary-statistics" class="level2">
<h2 data-anchor-id="summary-statistics">2. Summary Statistics</h2>
<p><strong>Table 1:</strong> Statistical summary of Mozambique.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(31, 58, 95, 1) !important;">Indicator</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(31, 58, 95, 1) !important;">Value</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(31, 58, 95, 1) !important;">Unit</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(31, 58, 95, 1) !important;">Year</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(31, 58, 95, 1) !important;">Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Total population</td>
<td style="text-align: left;">35,631,653</td>
<td style="text-align: left;">count</td>
<td style="text-align: left;">2025</td>
<td style="text-align: left;"><a href="https://data.worldbank.org/country/mozambique">World Bank WDI SP.POP.TOTL</a></td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Population at risk</td>
<td style="text-align: left;">34,631,766</td>
<td style="text-align: left;">count</td>
<td style="text-align: left;">2024</td>
<td style="text-align: left;"><a href="https://www.who.int/publications/m/item/annexes-world-malaria-report-2025">WMR 2025 Annex 4H/4I</a></td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Prevalence by RDT, children 6-59 months</td>
<td style="text-align: left;">32.3</td>
<td style="text-align: left;">%</td>
<td style="text-align: left;">2022-23</td>
<td style="text-align: left;"><a href="https://api.dhsprogram.com/rest/dhs/">IDS 2022-23</a></td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Estimated incidence</td>
<td style="text-align: left;">295.1</td>
<td style="text-align: left;">per 1000 pop at risk</td>
<td style="text-align: left;">2024</td>
<td style="text-align: left;"><a href="https://www.who.int/publications/m/item/annexes-world-malaria-report-2025">Derived from Annex 4H</a></td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Estimated mortality rate</td>
<td style="text-align: left;">51.8</td>
<td style="text-align: left;">per 100000 pop at risk</td>
<td style="text-align: left;">2024</td>
<td style="text-align: left;"><a href="https://www.who.int/publications/m/item/annexes-world-malaria-report-2025">Derived from Annex 4H</a></td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Urban population</td>
<td style="text-align: left;">37.2</td>
<td style="text-align: left;">%</td>
<td style="text-align: left;">2025</td>
<td style="text-align: left;"><a href="https://data.worldbank.org/country/mozambique">World Bank WDI SP.URB.TOTL.IN.ZS</a></td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">Capital city</td>
<td style="text-align: left;">Maputo</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">INE</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">Employment in agriculture</td>
<td style="text-align: left;">73</td>
<td style="text-align: left;">%</td>
<td style="text-align: left;">2025</td>
<td style="text-align: left;"><a href="https://data.worldbank.org/country/mozambique">World Bank WDI SL.AGR.EMPL.ZS</a></td>
</tr>
</tbody>
</table>
</div>
</div>
<hr>
</section>
<section id="administrative-boundaries" class="level2">
<h2 data-anchor-id="administrative-boundaries">3. Administrative Boundaries</h2>
<p>Mozambique lies between latitudes 10°S to 27°S and longitudes 30°E to 41°E, occupying 799,380 km² along the south-east African coast. It is divided into eleven provinces, 154 statutory districts, 457 postos administrativos and 1,712 localidades, alongside a separate elected structure of 65 municipalities (OCHA, 2025). OCHA’s Common Operational Dataset renders 161 admin-2 units because it treats Maputo City’s seven distritos municipais as districts; use 161 for any geospatial work, since the DHIS2 organisation units, the facility registry and the SNT layers are all built on it. Health districts and administrative districts are identical, which is what makes district-level stratification operationally tractable.</p>
<p><img src="../submissions/mozambique/Images/Mozambique_StudyArea_Map.png" class="img-fluid" alt="Figure:"> <strong>Figure 1:</strong>Administrative geography of Mozambique: 11 provinces and 161 district-level units<br>
<strong>Source:</strong> OCHA Common Operational Dataset, 2025; <a href="https://data.humdata.org/dataset/cod-ab-moz">Subnational Administrative Boundaries (COD-AB)</a></p>
<hr>
</section>
<section id="malaria-situation" class="level2">
<h2 data-anchor-id="malaria-situation">4. Malaria Situation</h2>
<p>Mozambique contributes to more than 3.6% of globally observed malaria cases annually, one of five countries (alongside Nigeria, DRC, Ethiopia, and Uganda) that together account for over half of all global cases, and one of 11 high-burden African countries that account for roughly two-thirds of global cases and deaths (WMR, 2025). In Mozambique, close to half of pediatric admissions are due to malaria and a third of hospital deaths are attributed to malaria. Mozambique’s national programme reported about 11.5 million cases and 358 in-hospital deaths in 2024 (WHO’s modelled estimate for the same year is 10.2 million cases and 17,946 deaths) (WMR, 2025). Efforts to reduce transmission have resulted in some improvements cases fell 12% and deaths 1% between 2023 and 2024 but cyclones and extremist-group activity remain the greatest threats to this progress, as the resulting displacement, deaths, and breaks in service provision often leave societies vulnerable (WMR, 2024 &amp; WMR, 2025).</p>
<hr>
</section>
<section id="history-of-malaria" class="level2">
<h2 data-anchor-id="history-of-malaria">5. History of Malaria</h2>
<p>Mozambique’s modern programme dates to the re-establishment of the NMCP in 1982, but the decisive shift came in the mid-2000s, when failing mono therapies gave way to artemisinin-based combination therapy and intermittent preventive treatment in pregnancy began nationally (MISAU, 2006). Over the following decade the programme built out universal coverage vector control and parasitological diagnosis mass insecticide treated net campaigns, indoor residual spraying in selected high-burden districts and rapid diagnostic tests extended to community level under successive strategic plans in 2012, 2017 and 2023, with nationwide DHIS2 reporting from 2015 giving district-level routine data for the first time; since 2020 the emphasis has moved from uniform national coverage to subnational tailoring, with intervention packages assigned by stratum (MISAU, 2023; Swiss Tropical and Public Health Institute, 2020). The current mix combines pyrethroid chlorfenapyr nets deployed against widespread pyrethroid resistance, targeted IRS, IPTp, seasonal malaria chemoprevention in Nampula, universal testing with RDTs followed by artemether-lumefantrine and the R21 vaccine introduced in Zamb??zia in 2024 though cyclones, COVID-19 and post election unrest have repeatedly interrupted delivery and the 2023-2030 plan remains costed well beyond secured financing (Gavi, the Vaccine Alliance, 2024; Malaria Consortium, 2025; MISAU, 2023; OCHA, 2026).</p>
<p><img src="../submissions/mozambique/Images/figure_04_timeline.png" class="img-fluid" alt="Figure:"> <strong>Figure 2:</strong> Timeline of malaria policy changes and intervention milestones, Mozambique, 1982-2026. <strong>Source:</strong> NMCP Plano Estratégico 2023-2030; MISAU Strategic plan 2006-2009; SIS-MA; Gavi/UNICEF/WHO AFRO (2024); Malaria Consortium (2025); The Global Fund (2026)</p>
<hr>
</section>
<section id="malaria-indicator-summary" class="level2">
<h2 data-anchor-id="malaria-indicator-summary">6. Malaria Indicator Summary</h2>
<section id="a.-dhis2-derived-indicators-incidence" class="level3">
<h3 data-anchor-id="a.-dhis2-derived-indicators-incidence">6a. DHIS2-derived indicators (incidence)</h3>
<p><strong>Table 2:</strong> Malaria indicators from the national DHIS2 instance (SIS-MA), Mozambique, 2022.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-hover table-condensed caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(31, 58, 95, 1) !important;">Indicator</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(31, 58, 95, 1) !important;">Value</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(31, 58, 95, 1) !important;">Unit</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(31, 58, 95, 1) !important;">Ref</th>
</tr>
</thead>
<tbody>
<tr class="odd" data-grouplength="2">
<td colspan="4" style="background-color: #EEF2F7; color: #1F3A5F; font-weight: 600"><strong>Burden</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Malaria incidence</td>
<td style="text-align: left;">391.8</td>
<td style="text-align: left;">per 1000 pop at risk</td>
<td style="text-align: left;">Table 1</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Total malaria cases</td>
<td style="text-align: left;">12,405,868</td>
<td style="text-align: left;">count</td>
<td style="text-align: left;">Table 4</td>
</tr>
<tr class="even" data-grouplength="3">
<td colspan="4" style="background-color: #EEF2F7; color: #1F3A5F; font-weight: 600"><strong>Testing</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Patients tested</td>
<td style="text-align: left;">23,206,871</td>
<td style="text-align: left;">count</td>
<td style="text-align: left;">Table 4</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Test positivity rate</td>
<td style="text-align: left;">53.4</td>
<td style="text-align: left;">%</td>
<td style="text-align: left;">Table 4</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Share of cases confirmed</td>
<td style="text-align: left;">99.9</td>
<td style="text-align: left;">%</td>
<td style="text-align: left;">Table 4</td>
</tr>
<tr class="even" data-grouplength="1">
<td colspan="4" style="background-color: #EEF2F7; color: #1F3A5F; font-weight: 600"><strong>Who is affected</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Share of cases in children under five</td>
<td style="text-align: left;">42.1</td>
<td style="text-align: left;">%</td>
<td style="text-align: left;">Table 4</td>
</tr>
<tr class="even" data-grouplength="2">
<td colspan="4" style="background-color: #EEF2F7; color: #1F3A5F; font-weight: 600"><strong>Severity</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Severe cases</td>
<td style="text-align: left;">70,118</td>
<td style="text-align: left;">count</td>
<td style="text-align: left;">Table 4</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Reported malaria deaths</td>
<td style="text-align: left;">423</td>
<td style="text-align: left;">count</td>
<td style="text-align: left;">Table 4</td>
</tr>
<tr class="odd" data-grouplength="1">
<td colspan="4" style="background-color: #EEF2F7; color: #1F3A5F; font-weight: 600"><strong>Community</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Share of cases reported by CHWs</td>
<td style="text-align: left;">10.2</td>
<td style="text-align: left;">%</td>
<td style="text-align: left;">Table 5</td>
</tr>
<tr class="odd" data-grouplength="1">
<td colspan="4" style="background-color: #EEF2F7; color: #1F3A5F; font-weight: 600"><strong>Data quality</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Reporting completeness</td>
<td style="text-align: left;">96.9</td>
<td style="text-align: left;">%</td>
<td style="text-align: left;">Table 4</td>
</tr>
</tbody>
</table>
<p><em>Source: <a href="https://mesamalaria.org/wp-content/uploads/2025/04/MOZAMBIQUE-Malaria-Profile-PMI-FY-2024.pdf">SIS-MA (DHIS2), via PMI Mozambique Malaria Profile FY 2024</a> (2022 data). Retrieved via: National or partner report.</em></p>
</div>
</div>
</section>
<section id="b.-survey-derived-indicators-prevalence-mortality" class="level3">
<h3 data-anchor-id="b.-survey-derived-indicators-prevalence-mortality">6b. Survey-derived indicators (prevalence / mortality)</h3>
<p>Nationally representative household surveys provide the population-based measures that routine facility data cannot: parasite prevalence in children, net ownership and use, chemoprevention in pregnancy, and care-seeking for childhood fever. The table below draws on four rounds the 2011 DHS, 2015 AIS, 2018 MIS and 2022-23 DHS allowing each indicator to be read as a trajectory rather than a single point, with gaps shown as NA where an indicator was not measured in that round.</p>
<p><strong>Table 3:</strong> Malaria survey indicators.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-hover table-condensed caption-top table-sm table-striped small">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(31, 58, 95, 1) !important;">Indicator</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(31, 58, 95, 1) !important;">2022-23 DHS</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(31, 58, 95, 1) !important;">2018 MIS</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(31, 58, 95, 1) !important;">2015 AIS</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(31, 58, 95, 1) !important;">2011 DHS</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(31, 58, 95, 1) !important;">2003 DHS</th>
</tr>
</thead>
<tbody>
<tr class="odd" data-grouplength="2">
<td colspan="6" style="background-color: #EEF2F7; color: #1F3A5F; font-weight: 600"><strong>Malaria burden</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Prevalence by RDT, children 6-59 months</td>
<td style="text-align: center;">32.3<br>
<span style="font-size:0.85em;color:#6B6B6B">(28.3 to 36.3)</span></td>
<td style="text-align: center;">38.9<br>
<span style="font-size:0.85em;color:#6B6B6B">(33.9 to 43.9)</span></td>
<td style="text-align: center;">40.2<br>
<span style="font-size:0.85em;color:#6B6B6B">(35.4 to 45.1)</span></td>
<td style="text-align: center;">38.3<br>
<span style="font-size:0.85em;color:#6B6B6B">(34.8 to 41.8)</span></td>
<td style="text-align: center;">-</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Under-five mortality rate (per 1,000 live births)</td>
<td style="text-align: center;">60<br>
<span style="font-size:0.85em;color:#6B6B6B">(54 to 66)</span></td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">97<br>
<span style="font-size:0.85em;color:#6B6B6B">(89 to 105)</span></td>
<td style="text-align: center;">152<br>
<span style="font-size:0.85em;color:#6B6B6B">(142 to 163)</span></td>
</tr>
<tr class="even" data-grouplength="4">
<td colspan="6" style="background-color: #EEF2F7; color: #1F3A5F; font-weight: 600"><strong>Insecticide-treated nets (ITNs)</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Households with at least one ITN</td>
<td style="text-align: center;">56.5</td>
<td style="text-align: center;">82.2</td>
<td style="text-align: center;">66.0</td>
<td style="text-align: center;">51.4</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Population with access to an ITN</td>
<td style="text-align: center;">44.8</td>
<td style="text-align: center;">68.5</td>
<td style="text-align: center;">53.8</td>
<td style="text-align: center;">37.0</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Population who slept under an ITN</td>
<td style="text-align: center;">38.6</td>
<td style="text-align: center;">68.4</td>
<td style="text-align: center;">45.4</td>
<td style="text-align: center;">29.5</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Children under 5 who slept under an ITN</td>
<td style="text-align: center;">42.5</td>
<td style="text-align: center;">72.7</td>
<td style="text-align: center;">47.9</td>
<td style="text-align: center;">35.7</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="odd" data-grouplength="1">
<td colspan="6" style="background-color: #EEF2F7; color: #1F3A5F; font-weight: 600"><strong>Malaria in pregnancy</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Women with 3+ doses of SP/Fansidar in pregnancy</td>
<td style="text-align: center;">25.3</td>
<td style="text-align: center;">40.6</td>
<td style="text-align: center;">23.3</td>
<td style="text-align: center;">9.5</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="odd" data-grouplength="3">
<td colspan="6" style="background-color: #EEF2F7; color: #1F3A5F; font-weight: 600"><strong>Case management, children with fever</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Advice or treatment sought</td>
<td style="text-align: center;">63.6</td>
<td style="text-align: center;">68.6</td>
<td style="text-align: center;">21.3</td>
<td style="text-align: center;">61.1</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Blood taken for testing</td>
<td style="text-align: center;">51.2</td>
<td style="text-align: center;">47.9</td>
<td style="text-align: center;">39.6</td>
<td style="text-align: center;">29.8</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-left: 2em;" data-indentlevel="1">Took an artemisinin-based combination</td>
<td style="text-align: center;">18.5</td>
<td style="text-align: center;">32.2</td>
<td style="text-align: center;">35.6</td>
<td style="text-align: center;">17.9</td>
<td style="text-align: center;">-</td>
</tr>
</tbody>
</table>
<p><em>Source: ICF, 2015. The DHS Program STATcompiler. Funded by USAID. <a href="http://www.statcompiler.com">www.statcompiler.com</a>. September 13 2026 (export file: STATcompilerExport2026913_17924.xlsx). Confidence intervals are shown for prevalence and mortality. A dash means the indicator was not measured in that survey.</em></p>
</div>
</div>
<hr>
</section>
</section>
<section id="health-system" class="level2">
<h2 data-anchor-id="health-system">7. Health System</h2>
<p>Public health services cater to approximately 60% of the population, with private facilities serving about 10%. There has been progressive investment in health infrastructure, particularly rural healthcare. The health sector is coordinated nationally by the Ministry of Health (MISAU), with implementation devolved to Provincial Health Directorates (DPS) and District Health Services (SDSMAS). There is efforts to decentralize resources and decision-making authority from central to provincial level. The healthcare system is hierarchically structured into four levels: Level I &amp; II: Primary care, peripheral facilities (health posts and rural clinics) Level III &amp; IV: Secondary and tertiary care with specialized services.</p>
<p><img src="../submissions/mozambique/Images/MozambiqueHS-diagram.png" class="img-fluid" alt="Figure:"> <strong>Figure 3</strong> Organisation of Health Administration and Service deliver.</p>
<p><strong>Source:</strong> (Herieth-version-1, 2024)</p>
<p><em>Community Health Workers (CHWs):</em></p>
<p>CHWs, locally known as Agentes Polivalentes Elementares (APEs) play a critical role in healthcare delivery, especially in remote areas.There are 17,648 deployed out of 18,000 planned and 5595 of these are involved in diagnosing and treating uncomplicated malaria as well as promoting preventive measures, and referring severe cases. APEs are keystone for malaria control in rural and remote areas.</p>
<p>Mozambique transitioned from paper based reporting that was aggregated at district, provincial and national level to a DHIS2 based system in 2015. While the initial approach was reliable and consistent, the quality of data did not meet malaria control management needs. Currently a full information M&amp;E system based on the DHIS2 platform collects malaria data. This includes outpatient attendance, testing, and confirmed cases, with dis aggregation by age and gender. Facilities with electronic systems fill data directly to the system and paper based records are entered into the system by District health teams . Efforts are underway to strengthen real-time data availability for decision-making.</p>
<p><img src="../submissions/mozambique/Images/Mozambique data Flow.png" class="img-fluid" alt="Figure:"> <strong>Figure 4</strong> Health data and information flow.</p>
<p><strong>Source:</strong> (Herieth-version-1, 2024)</p>
<p>Surveys like IMASIDA (Immunization, Malaria, HIV Indicators Survey) provide periodic data on treatment-seeking behavior, bed-net use, and coverage of interventions. Indicators tracked include Outpatient visits for suspected malaria , Laboratory-confirmed cases by rapid diagnostic tests (RDTs) with Age-disaggregated data on positive cases as well as bed-net coverage and use.</p>
<p><strong>Geographic Locations of Health Facilities</strong></p>
<p>The 1,295 geolocated facilities are unevenly distributed across the eleven provinces, with Zambezia (186), Sofala (185) and Nampula (175) together holding 42% of the national total, while Cidade de Maputo accounts for just 26. Density tells a different story from counts: Cidade de Maputo has 750 facilities per 10,000 km and Maputo Province 39, against 10 in Niassa and 11 in Tete the two largest and most sparsely served provinces, where a single facility must cover roughly ten times the area it does in the south.</p>
<p><img src="../submissions/mozambique/Images/12_facilities_by_province_summary.png" class="img-fluid" alt="Figure:"> <strong>Figure 5</strong> Health Facilities by Province Rank.</p>
<p><strong>Source:</strong>The Humanitarian Data Exchange https://data.humdata.org/dataset/mozambique-health-facilities</p>
<p>Facilities cluster along the coastal corridor and the main road and river axes, leaving interior districts of Niassa, Tete and western Zambezia with visible gaps, and the 54 hospitals are more concentrated still 10 in Nampula and 5 in Cidade de Maputo alone so referral capacity for severe malaria sits mainly in provincial capitals and coastal towns.</p>
<p><img src="../submissions/mozambique/Images/12_facilities_points_map.png" class="img-fluid" alt="Figure:"> <strong>Figure 6</strong> Geolocated health facilities by tier, Mozambique (n = 1,295)</p>
<p><strong>Source:</strong>The Humanitarian Data Exchange https://data.humdata.org/dataset/mozambique-health-facilities</p>
<hr>
</section>
<section id="stratification-maps-snt" class="level2">
<h2 data-anchor-id="stratification-maps-snt">8. Stratification Maps / SNT</h2>
<p>Mozambique incorporated maps to inform decision making and planning . A structured approach to optimizing malaria interventions in Mozambique involves using complementary analytical methods. It begins with spatial analysis of malaria burden to prioritize high-impact areas. Empirical data analysis and mathematical models help refine intervention targeting by evaluating past interventions and predicting optimal strategies. Cost-effectiveness analysis ensures interventions maximize case reductions within a fixed budget over five years. Finally, operational feasibility adjustments account for logistical and geographic constraints, ensuring interventions are practical and effectively implemented. This multi-faceted approach enhances the impact and efficiency of malaria control efforts.In addition to prevalence and incidence maps , risk maps and vulnerability to epidemics are mapped at district level. This aids with tailoring of interventions.</p>
<p><img src="../submissions/mozambique/Images/incidencemza.jpg" class="img-fluid" alt="Figure:"> <strong>Figure 7:</strong> Malaria incidence trend at district level</p>
<p><strong>Source:</strong> National Malaria Strategic Plan (NMSP) of Mozambique: 2023 – 2030 https://mesamalaria.org/resource-hub/national-malaria-strategic-plan-nmsp-of-mozambique-2023-2030/</p>
<p><img src="../submissions/mozambique/Images/malaria deaths.jpg" class="img-fluid" alt="Figure:"> <strong>Figure 8:</strong> Malaria deaths trend at district level</p>
<p><strong>Source:</strong> National Malaria Strategic Plan (NMSP) of Mozambique: 2023 – 2030 https://mesamalaria.org/resource-hub/national-malaria-strategic-plan-nmsp-of-mozambique-2023-2030/</p>
<p><img src="../submissions/mozambique/Images/interventionsmza.jpg" class="img-fluid" alt="Figure:"> <strong>Figure 9:</strong> Tailored Intervention Packages based on burden</p>
<p><strong>Source:</strong> National Malaria Strategic Plan (NMSP) of Mozambique: 2023 – 2030 https://mesamalaria.org/resource-hub/national-malaria-strategic-plan-nmsp-of-mozambique-2023-2030/</p>
<p>Parasite prevalence by RDT in children aged 6–59 months follows a steep north–south gradient, exceeding 33% across the northern and central provinces and peaking at 54.7% in Nampula, falling to 10–20% in Tete, Inhambane and Manica, and approaching zero in the far south 5.7% in Gaza, 0.3% in Maputo Province and 0.0% in Cidade de Maputo (IDS 2022–23).</p>
<p><img src="../submissions/mozambique/Images/06_province_prevalence_map.png" class="img-fluid" alt="Figure:"> <strong>Figure 10</strong> Province prevalence of Children 6-59 months, household survey.</p>
<p><strong>Source:</strong> STATcompiler https://www.statcompiler.com</p>
<p><img src="../submissions/mozambique/Images/06_province_prevalence_summary.png" class="img-fluid" alt="Figure:"> <strong>Figure 11</strong> Province prevalence summary According to RDT.</p>
<p><strong>Source:</strong> STATcompiler https://www.statcompiler.com</p>
<hr>
</section>
<section id="environment-and-seasonality" class="level2">
<h2 data-anchor-id="environment-and-seasonality">9. Environment and Seasonality</h2>
<p>Transmission is sustained year-round by warm temperatures mean monthly temperature stays above 18 ℃ in every province except the Manica highlands, so the thermal threshold for sporogonic development of Plasmodium falciparum is rarely a constraint combined with low-lying coastal and riverine terrain and abundant surface water that provide continuous Anopheles breeding habitat (MISAU, 2023; NASA Langley Research Center, 2025). Intensity follows a north-south ecological gradient, from the wet, densely populated northern provinces to the drier south, with mean annual rainfall falling from 1,403 mm in Nampula to 605 mm in Gaza and mean annual temperature ranging from 25.4 ℃ in Zambezia down to 21.2 ℃ on the Manica plateau, the one area cool enough in June-August (16.3 ℃ in July) to slow the parasite’s development materially (NASA Langley Research Center, 2025). Because temperature is permissive almost everywhere, rainfall sets the timing: a single wet season from December to April concentrates precipitation 362 mm in January in the north against 128 mm in the south and with cases lagging rainfall by roughly six to ten weeks, the malaria peak falls in January-March, earlier and sharper in the north and centre than in the south, where transmission is lower and more seasonal (Harp et al., 2021; MISAU, 2023).</p>
<p><img src="../submissions/mozambique/Images/11_rainfall_climatology.png" class="img-fluid" alt="Figure:"> <strong>Figure 12:</strong> Mean Monthly Rainfall (mm), 1991-2020</p>
<p><strong>Source:</strong> NASA POWER, parameter PRECTOTCORR (precipitation corrected, MERRA-2), 30-year climatology January 1991 – December 2020, retrieved at each province’s representative interior point via the POWER Climatology API. https://power.larc.nasa.gov/</p>
<p><img src="../submissions/mozambique/Images/12_rainfall_maps.png" class="img-fluid" alt="Figure:"> <strong>Figure 13:</strong> Rainfall zones and mean annual rainfall by province, Mozambique</p>
<p><strong>Source:</strong> NASA POWER, parameter PRECTOTCORR (precipitation corrected, MERRA-2), 30-year climatology January 1991 – December 2020, retrieved at each province’s representative interior point via the POWER Climatology API. https://power.larc.nasa.gov/</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../submissions/mozambique/Images/Screenshot 2025-02-04 120353.png" class="img-fluid figure-img"></p>
<figcaption><strong>Figure:</strong></figcaption>
</figure>
</div>
<p><strong>Figure 14:</strong> Variation of Malaria Cases and rainfall patterns</p>
<p><strong>Source:</strong> Inter-annual Climate Variability and Malaria in Mozambique https://agupubs.onlinelibrary.wiley.com/doi/pdfdirect/10.1029/2020GH000322</p>
<hr>
</section>
<section id="vector-profile" class="level2">
<h2 data-anchor-id="vector-profile">10. Vector Profile</h2>
<p>Malaria transmission in Mozambique is sustained by three primary vectors Anopheles funestus, An. arabiensis and An. gambiae sensu stricto with the saltwater breeding An. merus contributing along the southern and central coast; species-distribution models place An. funestus and An. arabiensis across virtually the whole country, while An. gambiae s.s. is concentrated in the wetter north and centre and An. merus is restricted to the coastal strip (Sinka et al., 2010; Wiebe et al., 2017). Recent entomological work documents multiple insecticide resistance in An.funestus: mosquitoes collected in Mopeia, Zambézia, in 2021–22 showed 14% mortality to deltamethrin, 37% to bendiocarb and 67% to pirimiphos-methyl, and pre-exposure to piperonyl butoxide raised deltamethrin mortality from 8% to 80%, implicating cytochrome P450 monooxygenases (Kiuru et al., 2025). That P450-mediated pyrethroid resistance is the operational rationale for the shift to dual-active-ingredient and PBO nets and for rotating IRS products away from pyrethroids.</p>
<p><img src="../submissions/mozambique/Images/15_vector_distribution.png" class="img-fluid" alt="Figure:"> <strong>Figure 15:</strong> Distribution of the major malaria vectors by district, Mozambique <strong>Source:</strong>.malariaAtlas :https://data.malariaatlas.org/</p>
<p><strong>Vector and parasite species</strong></p>
<p>Malaria in Mozambique is primarily caused by Plasmodium falciparum, the most virulent malaria parasite. The disease is transmitted by various Anopheles mosquito species, with Anopheles gambiae being dominant in the northern and central regions, while An. funestus is widespread along the coast. In the south and central areas, An. arabiensis is a key vector. An emerging concern is An. stephensi, which poses a growing threat, particularly in urban environments.</p>
<p><strong>Table 4:</strong> Vectors and Parasite species summary.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Metric</th>
<th style="text-align: left;">Mozambique</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mosquito species</td>
<td style="text-align: left;"><em>Anopheles gambiae</em> s.s., <em>An. arabiensis</em>, and <em>An. funestus</em> s.s.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Parasite</td>
<td style="text-align: left;"><em>Plasmodium falciparum</em></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Peak transmission season</td>
<td style="text-align: left;">October through March</td>
</tr>
<tr class="even">
<td style="text-align: left;">Drivers</td>
<td style="text-align: left;">Rainfall, altitude, cyclones</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Extreme weather events</td>
<td style="text-align: left;">Cyclones, Flood</td>
</tr>
<tr class="even">
<td style="text-align: left;">Weather type</td>
<td style="text-align: left;">Tropical to subtropical</td>
</tr>
</tbody>
</table>
<p>Insecticide resistance in Mozambique has followed a clear trajectory over twenty-five years of monitoring. In collections from 2000–02, Anopheles funestus s.s. was already pyrethroid-resistant in the far south but fully susceptible to DDT and to the organophosphate malathion everywhere tested (Casimiro et al., 2006). By 2006–10 the same pyrethroid resistance had reached central Mozambique, appearing in An. funestus in Mocuba, Zambézia, while DDT and deltamethrin still killed 100% of mosquitoes (Abílio et al., 2011). In collections from 2021–22 in Mopeia, also Zambézia, An. funestus s.l. was resistant to all four classes tested 14% mortality to deltamethrin, 37% to bendiocarb, 67% to pirimiphos-methyl and 79% to DDT with piperonyl butoxide restoring deltamethrin mortality from 8% to 80% (Kiuru et al., 2025). Two features of that last result matter operationally: the organophosphate reading, because pirimiphos-methyl is a mainstay IRS product, and the PBO restoration, because it identifies cytochrome P450 monooxygenases as the mechanism and is the direct evidence base for PBO and dual-active-ingredient nets</p>
<section id="table-9a.insecticide-susceptibility-of-malaria-vectors-mozambique-20002022" class="level3">
<h3 data-anchor-id="table-9a.insecticide-susceptibility-of-malaria-vectors-mozambique-20002022">Table 9a.Insecticide susceptibility of malaria vectors, Mozambique, 2000–2022</h3>
<p><strong>Table 5:</strong> Insecticides susceptibility.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Year of collection</th>
<th style="text-align: left;">Species</th>
<th style="text-align: left;">Insecticide (class)</th>
<th style="text-align: left;">Result</th>
<th style="text-align: left;">Sites</th>
<th style="text-align: left;">Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2000–02</td>
<td style="text-align: left;"><em>An. funestus</em> s.s.</td>
<td style="text-align: left;">Lambda-cyhalothrin (pyrethroid)</td>
<td style="text-align: left;">Resistant at 7 southern sites; susceptible elsewhere</td>
<td style="text-align: left;">19 districts nationally</td>
<td style="text-align: left;">Casimiro et al.&nbsp;(2006)</td>
</tr>
<tr class="even">
<td style="text-align: left;">2000–02</td>
<td style="text-align: left;"><em>An. funestus</em> s.s.</td>
<td style="text-align: left;">Deltamethrin, permethrin (pyrethroid)</td>
<td style="text-align: left;">Resistant populations in the south</td>
<td style="text-align: left;">Southern region</td>
<td style="text-align: left;">Casimiro et al.&nbsp;(2006)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2000–02</td>
<td style="text-align: left;"><em>An. funestus</em> s.s.</td>
<td style="text-align: left;">DDT (organochlorine)</td>
<td style="text-align: left;">Fully susceptible at all localities</td>
<td style="text-align: left;">19 districts nationally</td>
<td style="text-align: left;">Casimiro et al.&nbsp;(2006)</td>
</tr>
<tr class="even">
<td style="text-align: left;">2000–02</td>
<td style="text-align: left;"><em>An. funestus</em> s.s.</td>
<td style="text-align: left;">Malathion (organophosphate)</td>
<td style="text-align: left;">Fully susceptible at all sites</td>
<td style="text-align: left;">19 districts nationally</td>
<td style="text-align: left;">Casimiro et al.&nbsp;(2006)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2000–02</td>
<td style="text-align: left;"><em>An. funestus</em> s.s.</td>
<td style="text-align: left;">Bendiocarb (carbamate)</td>
<td style="text-align: left;">Low-level resistance at 5 localities</td>
<td style="text-align: left;">National</td>
<td style="text-align: left;">Casimiro et al.&nbsp;(2006)</td>
</tr>
<tr class="even">
<td style="text-align: left;">2000–02</td>
<td style="text-align: left;"><em>An. funestus</em> s.s.</td>
<td style="text-align: left;">Propoxur (carbamate)</td>
<td style="text-align: left;">Low-level resistance at 4 localities</td>
<td style="text-align: left;">National</td>
<td style="text-align: left;">Casimiro et al.&nbsp;(2006)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2006–10</td>
<td style="text-align: left;"><em>An. funestus</em> s.s.</td>
<td style="text-align: left;">Lambda-cyhalothrin (pyrethroid)</td>
<td style="text-align: left;">82.9–84.5% resistant</td>
<td style="text-align: left;">Zambézia (Mocuba and 5 other districts)</td>
<td style="text-align: left;">Abílio et al.&nbsp;(2011)</td>
</tr>
<tr class="even">
<td style="text-align: left;">2006–10</td>
<td style="text-align: left;"><em>An. funestus</em> s.s.</td>
<td style="text-align: left;">Bendiocarb (carbamate)</td>
<td style="text-align: left;">84.5% resistant</td>
<td style="text-align: left;">Zambézia</td>
<td style="text-align: left;">Abílio et al.&nbsp;(2011)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2006–10</td>
<td style="text-align: left;"><em>An. funestus</em> s.s.</td>
<td style="text-align: left;">Permethrin (pyrethroid)</td>
<td style="text-align: left;">99.4% susceptible</td>
<td style="text-align: left;">Zambézia</td>
<td style="text-align: left;">Abílio et al.&nbsp;(2011)</td>
</tr>
<tr class="even">
<td style="text-align: left;">2006–10</td>
<td style="text-align: left;"><em>An. funestus</em>, <em>An. gambiae</em> s.s., <em>An. arabiensis</em></td>
<td style="text-align: left;">Deltamethrin (pyrethroid)</td>
<td style="text-align: left;">100% susceptible</td>
<td style="text-align: left;">Zambézia</td>
<td style="text-align: left;">Abílio et al.&nbsp;(2011)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2006–10</td>
<td style="text-align: left;"><em>An. funestus</em>, <em>An. gambiae</em> s.s., <em>An. arabiensis</em></td>
<td style="text-align: left;">DDT (organochlorine)</td>
<td style="text-align: left;">100% susceptible</td>
<td style="text-align: left;">Zambézia</td>
<td style="text-align: left;">Abílio et al.&nbsp;(2011)</td>
</tr>
<tr class="even">
<td style="text-align: left;">2021–22</td>
<td style="text-align: left;"><em>An. funestus</em> s.l.</td>
<td style="text-align: left;">Deltamethrin (pyrethroid)</td>
<td style="text-align: left;">14% resistant</td>
<td style="text-align: left;">Mopeia, Zambézia</td>
<td style="text-align: left;">Kiuru et al.&nbsp;(2025)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2021–22</td>
<td style="text-align: left;"><em>An. funestus</em> s.l.</td>
<td style="text-align: left;">Bendiocarb (carbamate)</td>
<td style="text-align: left;">37% resistant</td>
<td style="text-align: left;">Mopeia, Zambézia</td>
<td style="text-align: left;">Kiuru et al.&nbsp;(2025)</td>
</tr>
<tr class="even">
<td style="text-align: left;">2021–22</td>
<td style="text-align: left;"><em>An. funestus</em> s.l.</td>
<td style="text-align: left;">Pirimiphos-methyl (organophosphate)</td>
<td style="text-align: left;">67% resistant</td>
<td style="text-align: left;">Mopeia, Zambézia</td>
<td style="text-align: left;">Kiuru et al.&nbsp;(2025)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2021–22</td>
<td style="text-align: left;"><em>An. funestus</em> s.l.</td>
<td style="text-align: left;">DDT (organochlorine)</td>
<td style="text-align: left;">79% resistant</td>
<td style="text-align: left;">Mopeia, Zambézia</td>
<td style="text-align: left;">Kiuru et al.&nbsp;(2025)</td>
</tr>
</tbody>
</table>
</section>
<section id="table-9b.-resistance-mechanisms" class="level3">
<h3 data-anchor-id="table-9b.-resistance-mechanisms">Table 9b. Resistance mechanisms</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Year</th>
<th style="text-align: left;">Species</th>
<th style="text-align: left;">Finding</th>
<th style="text-align: left;">Sites</th>
<th style="text-align: left;">Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2000–02</td>
<td style="text-align: left;"><em>An. funestus</em> s.s.</td>
<td style="text-align: left;">Elevated cytochrome P450 monooxygenase, 2.5–3×</td>
<td style="text-align: left;">Bela-Vista, Boane, Catembe, Catuane, Maputo, Moamba, Mozal</td>
<td style="text-align: left;">Casimiro et al.&nbsp;(2006)</td>
</tr>
<tr class="even">
<td style="text-align: left;">2000–02</td>
<td style="text-align: left;"><em>An. funestus</em> s.s.</td>
<td style="text-align: left;">PBO pre-exposure raised lambda-cyhalothrin mortality 55% → 97%</td>
<td style="text-align: left;">Beluluane</td>
<td style="text-align: left;">Casimiro et al.&nbsp;(2006)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2000–02</td>
<td style="text-align: left;"><em>An. funestus</em> s.s.</td>
<td style="text-align: left;">Altered acetylcholinesterase at low frequency</td>
<td style="text-align: left;">Nationwide</td>
<td style="text-align: left;">Casimiro et al.&nbsp;(2006)</td>
</tr>
<tr class="even">
<td style="text-align: left;">2000–02</td>
<td style="text-align: left;"><em>An. funestus</em> s.s.</td>
<td style="text-align: left;">Elevated general esterase</td>
<td style="text-align: left;">Bela-Vista, Boane, Quelimane</td>
<td style="text-align: left;">Casimiro et al.&nbsp;(2006)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2021–22</td>
<td style="text-align: left;"><em>An. funestus</em> s.l.</td>
<td style="text-align: left;">PBO pre-exposure raised deltamethrin mortality 8% → 80% (P450-mediated)</td>
<td style="text-align: left;">Mopeia, Zambézia</td>
<td style="text-align: left;">Kiuru et al.&nbsp;(2025)</td>
</tr>
<tr class="even">
<td style="text-align: left;">2021–22</td>
<td style="text-align: left;"><em>An. funestus</em> s.l.</td>
<td style="text-align: left;"><em>Rdl</em> allele frequency 0.49</td>
<td style="text-align: left;">Mopeia, Zambézia</td>
<td style="text-align: left;">Kiuru et al.&nbsp;(2025)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2021–22</td>
<td style="text-align: left;"><em>An. funestus</em> s.l.</td>
<td style="text-align: left;">6.5 kb structural variant, allele frequency 0.92</td>
<td style="text-align: left;">Mopeia, Zambézia</td>
<td style="text-align: left;">Kiuru et al.&nbsp;(2025)</td>
</tr>
<tr class="even">
<td style="text-align: left;">2021–22</td>
<td style="text-align: left;"><em>An. funestus</em> s.l.</td>
<td style="text-align: left;">L119F-<em>GSTe2</em>, allele frequency 0.05</td>
<td style="text-align: left;">Mopeia, Zambézia</td>
<td style="text-align: left;">Kiuru et al.&nbsp;(2025)</td>
</tr>
</tbody>
</table>
<p>Population-level ITN use fell from 68.4% in 2018 to 38.6% in 2022–23, even though 72.3% of the nets households owned were slept under the previous night the decline is a gap in net supply and access, not in willingness to use one (INE &amp; ICF, 2023). That reduced coverage now has to work against vectors that survive the insecticide the nets carry: in Mopeia, Zambézia a province where only 32.7% of the population slept under a net Anopheles funestus s.l. showed 14% mortality to deltamethrin, so each net delivers considerably less personal and community protection than the coverage figure alone implies (Kiuru et al., 2025). The shift to PBO and dual-active-ingredient nets addresses the insecticide half of this, since piperonyl butoxide restored deltamethrin mortality from 8% to 80% in that same population, but a better net reaching fewer than four people in ten cannot by itself recover the protection lost since 2018.</p>
<p><img src="../submissions/mozambique/Images/07_province_itn_use_map.png" class="img-fluid" alt="Figure:"> <strong>Figure 16:</strong> Population slept under an ITN the previous night, 2011-2023</p>
<p><strong>Source:</strong> STATcompiler https://www.statcompiler.com</p>
<p><img src="../submissions/mozambique/Images/07_province_itn_use_summary.png" class="img-fluid" alt="Figure:"> <strong>Figure 17:</strong> ITN Use 2022-2023 IDS summary</p>
<p><strong>Source:</strong> STATcompiler https://www.statcompiler.com</p>
<hr>
</section>
</section>
<section id="references" class="level2">
<h2 data-anchor-id="references">11. References</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Title</th>
<th style="text-align: left;">URL</th>
<th style="text-align: left;">Description</th>
<th style="text-align: left;">Tag</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PMI MOP</td>
<td style="text-align: left;">https://www.pmi.gov/wp-content/uploads/2024/04/FY-2024-Mozambique-MOP-1.pdf</td>
<td style="text-align: left;">Planned PMI activities, commodity quantities and budget by intervention</td>
<td style="text-align: left;">Intervention</td>
</tr>
<tr class="even">
<td style="text-align: left;">National Strategic Plan 2023</td>
<td style="text-align: left;">https://drive.google.com/file/d/1pwltiFoG4WESYsBspG4SR4nTJyyrmaE_/view</td>
<td style="text-align: left;">Targets, stratification method, costed intervention packages, funding gap</td>
<td style="text-align: left;">Policy/Strategic Plan</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DHS STATcompiler</td>
<td style="text-align: left;">https://www.statcompiler.com/</td>
<td style="text-align: left;">Survey indicators: prevalence, ITN use, IPTp, care-seeking, by province and survey</td>
<td style="text-align: left;">Epidemiology</td>
</tr>
<tr class="even">
<td style="text-align: left;">RHIS</td>
<td style="text-align: left;">https://drive.google.com/file/d/1_qfr-xuowp4cPTpSH28I695BYzwLDtKe/view</td>
<td style="text-align: left;">Structure and indicator definitions of the routine reporting system</td>
<td style="text-align: left;">Health System</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Epidemiology and control profile of malaria in Mozambique</td>
<td style="text-align: left;">https://web-archive.lshtm.ac.uk/www.linkmalaria.org/sites/link/files/content/country/profiles/Mozambique-profile-web.pdf</td>
<td style="text-align: left;">Earlier country profile; historical baseline for burden, vectors and control</td>
<td style="text-align: left;">Epidemiology</td>
</tr>
<tr class="even">
<td style="text-align: left;">Interannual Climate Variability and Malaria in Mozambique</td>
<td style="text-align: left;">https://agupubs.onlinelibrary.wiley.com/doi/pdfdirect/10.1029/2020GH000322</td>
<td style="text-align: left;">Rainfall–case lag and interannual climate effects on transmission</td>
<td style="text-align: left;">Epidemiology</td>
</tr>
<tr class="odd">
<td style="text-align: left;">End Malaria Global Community Health Dashboard</td>
<td style="text-align: left;">https://dashboards.endmalaria.org/en/global-community-health</td>
<td style="text-align: left;">CHW coverage and community case management indicators</td>
<td style="text-align: left;">Health System</td>
</tr>
<tr class="even">
<td style="text-align: left;">WHO World Malaria Report 2025 annexes</td>
<td style="text-align: left;">https://www.who.int/teams/global-malaria-programme/reports/world-malaria-report-2025</td>
<td style="text-align: left;">Burden 2000–2024, routine surveillance, commodities, financing, policy adoption</td>
<td style="text-align: left;">Epidemiology</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PMI Mozambique Malaria Profile FY 2024</td>
<td style="text-align: left;">https://mesamalaria.org/wp-content/uploads/2025/04/MOZAMBIQUE-Malaria-Profile-PMI-FY-2024.pdf</td>
<td style="text-align: left;">DHIS2/SIS-MA indicator table for 2022, explicitly attributed; SNT stratification and district incidence maps</td>
<td style="text-align: left;">Epidemiology</td>
</tr>
<tr class="even">
<td style="text-align: left;">SIS-MA national DHIS2 instance</td>
<td style="text-align: left;">https://sisma.misau.gov.mz/</td>
<td style="text-align: left;">Source of all routine malaria indicators</td>
<td style="text-align: left;">Health System</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Strategic plan for malaria control in Mozambique 2006–2009</td>
<td style="text-align: left;">https://afro.who.int/sites/default/files/2017-06/Strategic%20plan%20for%20malaria%20control%20in%20Mozambique.pdf</td>
<td style="text-align: left;">Dates treatment policy changes: AQ+SP 2002, artesunate+SP late 2004, IPTp 2006</td>
<td style="text-align: left;">Policy/Strategic Plan</td>
</tr>
<tr class="even">
<td style="text-align: left;">R21/Matrix-M malaria vaccine introduction, August 2024</td>
<td style="text-align: left;">https://www.gavi.org/news/media-room/mozambique-introduces-malaria-vaccines-routine-immunization</td>
<td style="text-align: left;">Dates and geography of vaccine roll out (Zambézia, 22 districts)</td>
<td style="text-align: left;">Intervention</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Malaria Consortium SMC in Mozambique</td>
<td style="text-align: left;">https://www.malariaconsortium.org/country/mozambique</td>
<td style="text-align: left;">SMC pilot, scale-up and the 2024–25 Nampula cancellation</td>
<td style="text-align: left;">Intervention</td>
</tr>
<tr class="even">
<td style="text-align: left;">Multiple insecticide resistance in Anopheles funestus, Mopeia</td>
<td style="text-align: left;">https://doi.org/10.1186/s12936-025-05321-w</td>
<td style="text-align: left;">Phenotypic and molecular resistance, 2021–22; rationale for dual AI nets</td>
<td style="text-align: left;">Resistance</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Casimiro S et al.&nbsp;Insecticide resistance in Anopheles funestus from Mozambique (2006)</td>
<td style="text-align: left;">https://doi.org/10.1093/jmedent/43.2.267</td>
<td style="text-align: left;">National baseline, 19 districts 2000–02; the start of the resistance trajectory</td>
<td style="text-align: left;">Resistance</td>
</tr>
<tr class="even">
<td style="text-align: left;">Abílio AP et al.&nbsp;Emergence of insecticide resistance in central Mozambique (2011)</td>
<td style="text-align: left;">https://doi.org/10.1186/1475-2875-10-110</td>
<td style="text-align: left;">Zambézia 2006–10; the middle point showing resistance spreading north from the south</td>
<td style="text-align: left;">Resistance</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wiebe A et al.&nbsp;Geographical distributions of African malaria vector sibling species (2017)</td>
<td style="text-align: left;">https://doi.org/10.1186/s12936-017-1734-y</td>
<td style="text-align: left;">Source of the An. funestus, An. gambiae s.s. and An. merus distribution surfaces; CC BY 4.0 attribution is a licence condition</td>
<td style="text-align: left;">Vector Bionomics</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sinka ME et al.&nbsp;The dominant Anopheles vectors of human malaria in Africa (2010)</td>
<td style="text-align: left;">https://doi.org/10.1186/1756-3305-3-117</td>
<td style="text-align: left;">Source of the An. arabiensis distribution surface; bionomic précis per species</td>
<td style="text-align: left;">Vector Bionomics</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Malaria Atlas Project</td>
<td style="text-align: left;">https://data.malariaatlas.org/</td>
<td style="text-align: left;">Portal the vector rasters and occurrence points were downloaded from</td>
<td style="text-align: left;">Vector Bionomics</td>
</tr>
<tr class="even">
<td style="text-align: left;">OCHA- Administrative boundaries (COD-AB) Mozambique v02</td>
<td style="text-align: left;">https://data.humdata.org/dataset/cod-ab-moz</td>
<td style="text-align: left;">Province, district and posto boundaries used for every map; P-codes for joining</td>
<td style="text-align: left;">Health System</td>
</tr>
<tr class="odd">
<td style="text-align: left;">OCHA- Mozambique health facilities / Master Health Facility List</td>
<td style="text-align: left;">https://data.humdata.org/dataset/mozambique-health-facilities</td>
<td style="text-align: left;">1,295 geolocated facilities; source of the facility map (2017 vintage, CC0)</td>
<td style="text-align: left;">Health System</td>
</tr>
<tr class="even">
<td style="text-align: left;">NASA POWER climatology (PRECTOTCORR, T2M), 1991–2020</td>
<td style="text-align: left;">https://power.larc.nasa.gov/</td>
<td style="text-align: left;">Rainfall and temperature by zone and province, MERRA-2 reanalysis; basis of the seasonality figure</td>
<td style="text-align: left;">Epidemiology</td>
</tr>
</tbody>
</table>
<hr>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/map-data-engineering\.github\.io\/COUNTRIES-PROFILES\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 MAP Data Engineering Team</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Malaria Country Profiles</p>
</div>
  </div>
</footer>




</body></html>